config/routes.rb
Rails.application.routes.draw do
  coord_regex = /(\-)?\d+(\.\d+)?/

  get 'cities/:lat/:lng', to: 'cities#show', lat: coord_regex, lng: coord_regex
  get 'cities', to: 'cities#show'
  get '/:lat/:lng', to: 'cities#index', as: :city, lat: coord_regex, lng: coord_regex

  root to: 'cities#index'

  # Last route is a city search
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    # @city = params[:city]
    @lat = params[:lat]
    @lng = params[:lng]
  end

  def show
    query = { per_page: 1000 }

    if !params['lat'].blank? && !params['lng'].blank?
      query.merge!({
        lat: params['lat'],
        lng: params['lng'],
        zoom: 10
      })
    end

    @issues = see_click_fix.issues(query)['issues']
  end

  private
  def see_click_fix
    @endpoint ||= SeeClickFix::SeeClickFix.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/index.html.haml
%section#cities-content(data-lat="#{@lat}" data-lng="#{@lng}" data-handler='SeeClickFixVisualizer')
  %main
    %p Searching for Top 100 issues from #{link_to 'SeeClickFix', 'http://seeclickfix.com'}
    #map
    %small= link_to 'Lookup New Haven', city_path(lat: 41.3100, lng: -72.9263)

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Charting Playground

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

    = javascript_include_tag 'application', 'data-turbolinks-track' => true